function padding_bools = parse_padding(padding)
if strcmp(padding,'symmetric')
    padding_bools = struct( ...
        'is_symmetric',true, ...
        'is_periodic',false, ...
        'is_zero',false);
elseif strcmp(padding,'periodic')
    padding_bools = struct( ...
        'is_symmetric',false, ...
        'is_periodic',true, ...
        'is_zero',false);
elseif strcmp(padding,'zero')
    padding_bools = struct( ...
        'is_symmetric',false, ...
        'is_periodic',false, ...
        'is_zero',true);
else
    error('unrecognized padding string');
end
