function S_bools = parse_invariance(invariance)
if strcmp(invariance,'blurred')
    S_bools = struct( ...
        'is_blurred',true, ...
        'is_bypassed',false, ...
        'is_pooled',false);
elseif strcmp(invariance,'pooled')
    S_bools = struct( ...
        'is_blurred',false, ...
        'is_bypassed',false, ...
        'is_pooled',true);
elseif strcmp(invariance,'bypassed')
    S_bools = struct( ...
        'is_blurred',false, ...
        'is_bypassed',true, ...
        'is_pooled',false);
else
    error('unrecognized invariance string');
end
