function phi_bools = parse_phi(phi_string)
switch phi_string
    case 'by_substraction'
        phi_bools = struct( ...
            'is_by_substraction', true, ...
            'is_gaussian', false, ...
            'is_rectangular', false);
    case 'gamma'
        phi_bools = struct( ...
            'is_by_substraction', false, ...
            'is_gamma', true, ...
            'is_gaussian', false, ...
            'is_rectangular');
    case 'gaussian'
        phi_bools = struct( ...
            'is_by_substraction', false, ...
            'is_gaussian', true, ...
            'is_rectangular', false);
    case 'rectangular'
        phi_bools = struct( ...
            'is_by_substraction', false, ...
            'is_gaussian', false, ...
            'is_rectangular', true);
            
end
end